hi
Tue 21 Mar 19:31:27 GMT 2023
compute-permanent-node-746
uid=10025(asa_cooper_stickland) gid=10012(owain_evans) groups=10012(owain_evans)
/data/asa_cooper_stickland/situational-awareness
doing it in one go
1
wandb: Currently logged in as: asacoopstick. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.14.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.10
wandb: Run data is saved locally in /data/asa_cooper_stickland/situational-awareness/wandb/run-20230321_193147-5voiel98
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run asa_reawrd_test (30025_0)
wandb: ‚≠êÔ∏è View project at https://wandb.ai/asacoopstick/reward-flan-t5
wandb: üöÄ View run at https://wandb.ai/asacoopstick/reward-flan-t5/runs/5voiel98
Loading model
Loading tokenizer and generating datasets
Failed to generate datasets, retrying
Failed to generate datasets, retrying
Failed to generate datasets, retrying
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run asa_reawrd_test (30025_0) at: https://wandb.ai/asacoopstick/reward-flan-t5/runs/5voiel98
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230321_193147-5voiel98/logs
Traceback (most recent call last):
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 213, in <module>
    train(project=args.project,
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 87, in train
    raise e
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 79, in train
    wandb.config.data_dir, wandb.config.data_path, tokenizer, max_length=512, is_cot=is_cot_eval, reward=wandb.reward)
AttributeError: module 'wandb' has no attribute 'reward'
